//DILARANG MEMPERJUAL BELI SC NYA! MAU REUPLOAD? TARO CREDIT GW ALDOUS FT VAN. EMANG ANJ LO JUAL SC GW MINIMAL BIKIN SC SENDIRI DECK😂 
#DARKNES THE MAKER
#+6285380166282
#SC BOT V5
THANKS FOR MY SUBSCRIBER DONT FORGET TO SUBSCRIBE MY YOUTUBE CHANNEL Yt Maxxy Botz